version: '3.8'

services:
  db:
    image: postgres:16
    container_name: demo-postgres
    environment:
      POSTGRES_DB: demo-db
      POSTGRES_USER: demo-user
      POSTGRES_PASSWORD: demo-pass
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  demo-app:
    build: .
    environment:
      P_DB_NAME: "demo-db"
      P_PORT: "5432"
      P_USER: "demo-user"
      P_PASSWORD: "demo-pass"
      P_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started # Wait until 'db' container starts

volumes:
  db_data: